[general]
import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
#family = "CaskaydiaCove Nerd Font"
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"
