"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$hostname\
[](bg:sky fg:surface0)\
$directory\
[](fg:sky bg:teal)\
$git_branch\
$git_status\
[](fg:teal bg:text)\
$swift\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:text bg:dark)\
$jobs\
$cmd_duration\
[ ](fg:dark)\
$line_break\
$character"""

palette = "catppuccin_latte"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Macos = " "

[directory]
style = "fg:base bg:sky"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"dotfiles" = " "

[git_branch]
symbol = ""
style = "bg:teal fg:crust"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:teal fg:crust"
format = '[($all_status$ahead_behind )]($style)'
ahead = '⇡${count}'
behind = '⇣${count}'
staged = '+${count}'
modified = '!${count}'
stashed = '$${count}'

[swift]
symbol = ""
style = "bg:text fg:mantle"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = ""
style = "bg:text fg:mantle"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:text fg:mantle"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:text fg:mantle"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bg:text fg:mantle"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[hostname]
style = "bg:surface0 fg:text"
format = '[ $ssh_symbol$hostname]($style)'

[cmd_duration]
format = '[$duration]($style)'
style = 'fg:bright_yellow bg:dark'

[jobs]
symbol = ' '
style = 'fg:red bg:dark'
format = '[$symbol$number  ]($style)'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
# RWC additions
dark = "#1d2230"
bright_yellow = "#ffff00"
